// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_imgback_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel8, 700);
    lv_obj_set_height(ui_Panel8, 350);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, -50);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Panel8);
    lv_img_set_src(ui_Image3, &ui_img_img_png);
    lv_obj_set_width(ui_Image3, 700);
    lv_obj_set_height(ui_Image3, 350);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton8 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img1_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton8, 75);
    lv_obj_set_height(ui_ImgButton8, 35);
    lv_obj_set_x(ui_ImgButton8, -344);
    lv_obj_set_y(ui_ImgButton8, 180);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    ui_ImgButton9 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img2_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton9, 75);
    lv_obj_set_height(ui_ImgButton9, 35);
    lv_obj_set_x(ui_ImgButton9, -258);
    lv_obj_set_y(ui_ImgButton9, 180);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_ImgButton10 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img7_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton10, 75);
    lv_obj_set_height(ui_ImgButton10, 35);
    lv_obj_set_x(ui_ImgButton10, 167);
    lv_obj_set_y(ui_ImgButton10, 180);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);

    ui_ImgButton11 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img6_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton11, 75);
    lv_obj_set_height(ui_ImgButton11, 35);
    lv_obj_set_x(ui_ImgButton11, 79);
    lv_obj_set_y(ui_ImgButton11, 180);
    lv_obj_set_align(ui_ImgButton11, LV_ALIGN_CENTER);

    ui_ImgButton12 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img5_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton12, 75);
    lv_obj_set_height(ui_ImgButton12, 35);
    lv_obj_set_x(ui_ImgButton12, -8);
    lv_obj_set_y(ui_ImgButton12, 180);
    lv_obj_set_align(ui_ImgButton12, LV_ALIGN_CENTER);

    ui_ImgButton13 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img4_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton13, 75);
    lv_obj_set_height(ui_ImgButton13, 35);
    lv_obj_set_x(ui_ImgButton13, -91);
    lv_obj_set_y(ui_ImgButton13, 180);
    lv_obj_set_align(ui_ImgButton13, LV_ALIGN_CENTER);

    ui_ImgButton14 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img3_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton14, 75);
    lv_obj_set_height(ui_ImgButton14, 35);
    lv_obj_set_x(ui_ImgButton14, -174);
    lv_obj_set_y(ui_ImgButton14, 180);
    lv_obj_set_align(ui_ImgButton14, LV_ALIGN_CENTER);

    ui_ImgButton15 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_exit_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton15, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_star_png, NULL);
    lv_obj_set_width(ui_ImgButton15, 50);
    lv_obj_set_height(ui_ImgButton15, 50);
    lv_obj_set_x(ui_ImgButton15, 345);
    lv_obj_set_y(ui_ImgButton15, 181);
    lv_obj_set_align(ui_ImgButton15, LV_ALIGN_CENTER);

    ui_ImgButton17 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_img8_1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_10_png, NULL);
    lv_obj_set_width(ui_ImgButton17, 75);
    lv_obj_set_height(ui_ImgButton17, 35);
    lv_obj_set_x(ui_ImgButton17, 256);
    lv_obj_set_y(ui_ImgButton17, 180);
    lv_obj_set_align(ui_ImgButton17, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton11, ui_event_ImgButton11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton12, ui_event_ImgButton12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton13, ui_event_ImgButton13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton14, ui_event_ImgButton14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton15, ui_event_ImgButton15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton17, ui_event_ImgButton17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}
