// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen5, &ui_img_adback_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Screen5, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 100);
    lv_obj_set_height(ui_Spinner2, 100);
    lv_obj_set_x(ui_Spinner2, 349);
    lv_obj_set_y(ui_Spinner2, 140);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel9, 300);
    lv_obj_set_height(ui_Panel9, 400);
    lv_obj_set_x(ui_Panel9, -255);
    lv_obj_set_y(ui_Panel9, 43);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Panel9);
    lv_img_set_src(ui_Image4, &ui_img_16_png);
    lv_obj_set_width(ui_Image4, 300);
    lv_obj_set_height(ui_Image4, 400);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton16 = lv_imgbtn_create(ui_Screen5);
    lv_imgbtn_set_src(ui_ImgButton16, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_quit_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton16, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_star_png, NULL);
    lv_obj_set_width(ui_ImgButton16, 50);
    lv_obj_set_height(ui_ImgButton16, 50);
    lv_obj_set_x(ui_ImgButton16, -373);
    lv_obj_set_y(ui_ImgButton16, -200);
    lv_obj_set_align(ui_ImgButton16, LV_ALIGN_CENTER);

    ui_Label15 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 349);
    lv_obj_set_y(ui_Label15, 137);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "点击购买");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image5, &ui_img_17_png);
    lv_obj_set_width(ui_Image5, 100);
    lv_obj_set_height(ui_Image5, 100);
    lv_obj_set_x(ui_Image5, 340);
    lv_obj_set_y(ui_Image5, -100);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -10);
    lv_obj_set_y(ui_Label16, -197);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "每年卖出3亿杯，可绕地球三圈半");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image6, &ui_img_18_png);
    lv_obj_set_width(ui_Image6, 100);
    lv_obj_set_height(ui_Image6, 100);
    lv_obj_set_x(ui_Image6, -22);
    lv_obj_set_y(ui_Image6, -104);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 136);
    lv_obj_set_y(ui_Label17, -12);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "妈妈我就要喝可口可乐！");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image7, &ui_img_19_png);
    lv_obj_set_width(ui_Image7, 250);
    lv_obj_set_height(ui_Image7, 193);
    lv_obj_set_x(ui_Image7, 31);
    lv_obj_set_y(ui_Image7, 126);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image8, &ui_img_20_png);
    lv_obj_set_width(ui_Image8, 200);
    lv_obj_set_height(ui_Image8, 200);
    lv_obj_set_x(ui_Image8, 225);
    lv_obj_set_y(ui_Image8, 128);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image9, &ui_img_21_png);
    lv_obj_set_width(ui_Image9, 200);
    lv_obj_set_height(ui_Image9, 100);
    lv_obj_set_x(ui_Image9, 168);
    lv_obj_set_y(ui_Image9, -100);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton16, ui_event_ImgButton16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
