// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image10, &ui_img_22_png);
    lv_obj_set_width(ui_Image10, 400);
    lv_obj_set_height(ui_Image10, 300);
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, -10);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton18 = lv_imgbtn_create(ui_Screen6);
    lv_imgbtn_set_src(ui_ImgButton18, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_quit2_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton18, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_star_png, NULL);
    lv_obj_set_width(ui_ImgButton18, 50);
    lv_obj_set_height(ui_ImgButton18, 50);
    lv_obj_set_x(ui_ImgButton18, -350);
    lv_obj_set_y(ui_ImgButton18, -200);
    lv_obj_set_align(ui_ImgButton18, LV_ALIGN_CENTER);

    ui_Bar1 = lv_bar_create(ui_Screen6);
    lv_obj_set_width(ui_Bar1, 400);
    lv_obj_set_height(ui_Bar1, 30);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 200);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x1608A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x2BAB8E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -223);
    lv_obj_set_y(ui_Label19, -200);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "功德圆满");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image10, ui_event_Image10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton18, ui_event_ImgButton18, LV_EVENT_ALL, NULL);

}
