// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void ani1_Animation(lv_obj_t * TargetObject, int delay);
void an2_Animation(lv_obj_t * TargetObject, int delay);
void an3_Animation(lv_obj_t * TargetObject, int delay);
void an4_Animation(lv_obj_t * TargetObject, int delay);
void an5_Animation(lv_obj_t * TargetObject, int delay);
void an6_Animation(lv_obj_t * TargetObject, int delay);
void an7_Animation(lv_obj_t * TargetObject, int delay);
void an8_Animation(lv_obj_t * TargetObject, int delay);
void an9_Animation(lv_obj_t * TargetObject, int delay);
void an10_Animation(lv_obj_t * TargetObject, int delay);
void an11_Animation(lv_obj_t * TargetObject, int delay);
void an12_Animation(lv_obj_t * TargetObject, int delay);
void an13_Animation(lv_obj_t * TargetObject, int delay);
void an14_Animation(lv_obj_t * TargetObject, int delay);
void an15_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel5;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel6;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_ImgButton5;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_ImgButton19;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label24;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label10;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image3;
void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
void ui_event_ImgButton11(lv_event_t * e);
extern lv_obj_t * ui_ImgButton11;
void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
void ui_event_ImgButton14(lv_event_t * e);
extern lv_obj_t * ui_ImgButton14;
void ui_event_ImgButton15(lv_event_t * e);
extern lv_obj_t * ui_ImgButton15;
void ui_event_ImgButton17(lv_event_t * e);
extern lv_obj_t * ui_ImgButton17;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image4;
void ui_event_ImgButton16(lv_event_t * e);
extern lv_obj_t * ui_ImgButton16;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
void ui_event_ImgButton18(lv_event_t * e);
extern lv_obj_t * ui_ImgButton18;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_star_png);    // assets/star.png
LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(ui_img_9_png);    // assets/9.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_exit_png);    // assets/exit.png
LV_IMG_DECLARE(ui_img_23_png);    // assets/23.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_imgback_png);    // assets/imgback.png
LV_IMG_DECLARE(ui_img_img_png);    // assets/img.png
LV_IMG_DECLARE(ui_img_img1_1_png);    // assets/img1.1.png
LV_IMG_DECLARE(ui_img_10_png);    // assets/10.png
LV_IMG_DECLARE(ui_img_img1_png);    // assets/img1.png
LV_IMG_DECLARE(ui_img_img2_1_png);    // assets/img2.1.png
LV_IMG_DECLARE(ui_img_img2_png);    // assets/img2.png
LV_IMG_DECLARE(ui_img_img7_1_png);    // assets/img7.1.png
LV_IMG_DECLARE(ui_img_img7_png);    // assets/img7.png
LV_IMG_DECLARE(ui_img_img6_1_png);    // assets/img6.1.png
LV_IMG_DECLARE(ui_img_img6_png);    // assets/img6.png
LV_IMG_DECLARE(ui_img_img5_1_png);    // assets/img5.1.png
LV_IMG_DECLARE(ui_img_img5_png);    // assets/img5.png
LV_IMG_DECLARE(ui_img_img4_1_png);    // assets/img4.1.png
LV_IMG_DECLARE(ui_img_img4_png);    // assets/img4.png
LV_IMG_DECLARE(ui_img_img3_1_png);    // assets/img3.1.png
LV_IMG_DECLARE(ui_img_img3_png);    // assets/img3.png
LV_IMG_DECLARE(ui_img_img8_1_png);    // assets/img8.1.png
LV_IMG_DECLARE(ui_img_img8_png);    // assets/img8.png
LV_IMG_DECLARE(ui_img_adback_png);    // assets/adback.png
LV_IMG_DECLARE(ui_img_16_png);    // assets/16.png
LV_IMG_DECLARE(ui_img_quit_png);    // assets/quit.png
LV_IMG_DECLARE(ui_img_17_png);    // assets/17.png
LV_IMG_DECLARE(ui_img_18_png);    // assets/18.png
LV_IMG_DECLARE(ui_img_19_png);    // assets/19.png
LV_IMG_DECLARE(ui_img_20_png);    // assets/20.png
LV_IMG_DECLARE(ui_img_21_png);    // assets/21.png
LV_IMG_DECLARE(ui_img_22_png);    // assets/22.png
LV_IMG_DECLARE(ui_img_quit2_png);    // assets/quit2.png
LV_IMG_DECLARE(ui_img_13_png);    // assets/13.png
LV_IMG_DECLARE(ui_img_14_png);    // assets/14.png
LV_IMG_DECLARE(ui_img_15_png);    // assets/15.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
